#!/bin/sh
dire="/usr/share/qYaH3C"

mkdir -p $dire
cp -rf /application/* $dire/
ln -s $dire/qYaH3C.py /usr/bin/qyah3c

cp -f /qYaH3C.desktop /usr/share/applications/
cp -f /application/image/icon.png /usr/share/pixmaps/qYaH3C.png
