#!/bin/sh
dire="/usr/share/qYaH3C"

INSTALL_PATH="/usr/share/qYaH3C"
ICON_PATH="/usr/share/pixmaps"
APP_PATH="/usr/share/applications"
BIN_PATH=""

mkdir -p $dire
cp -rf /application/* $dire
ln -s $dire/qyah3c.py /usr/bin/qyah3c
cp -f /qYaH3C.desktop /usr/share/applications
cp -f /application/image/icon.png /usr/share/pixmaps/qYaH3C.png
